
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const ADD_QUESTION = 'ADD_QUESTION';
export const RECEIVE_ANSWERS = 'RECEIVE_ANSWERS';
export const ADD_ANSWER = 'ADD_ANSWER';
